### ISSUE TITLE
Refactor : 반응형 디자인 및 수정 필드 요구사항 정리

### ISSUE THREAD

**Issue by EthanJcoding** [starplanter93/The_Garden_of_Musicsheet#102]
## Description
기존에 작성한 코드를 수정하는 작업입니다.

## Todo
- [x] 마이페이지, 작성페이지 반응형 적용해보기 => 다른 이슈핸들링을 많이해서 따로 이슈파고 할게용
- [x] 악보 수정 요청시 필요한 필드 수정 또는 로직 추가해보기
- [x] 데이터 수정시 필드가 날아간 경우를 대비하여 아직 존재하는 컬랙션과 sync를 맞추는 로직 구현해보기 

## ETC
기타사항
눈에 보이는 지연 요소들을 사이드 이펙트를 생각해보며 제거해보겠습니다!

- [x] 헤더 미니 프로필에 데이터가 안들어가짐 ! ( 로그인 다시하면 보여지긴 함 ) => reducer 만들어서 닉네임 바꿀 때 상태 업데이트 해주기
- [x] 구글로 회원가입을 하면 유저 필드가 만들어지게 로직 넣어주기
- [x] 게시글 삭제 구현
- [x] 삭제된 게시글, 게시글 작성자가 탈퇴시 안보이게 만들기
- [x] 곡이 삭제된 상황에서 악보가 추가되면 되살아나는 로직 추가
