### ISSUE TITLE
Fix: 장바구니 모달 관련 여러 이슈 수정

### ISSUE THREAD

**Issue by starplanter93** [starplanter93/The_Garden_of_Musicsheet#131]
## Description
장바구니 모달 관련 여러 이슈 수정

## Todo
- [x] 카트 바디의 overflow 속성 auto로 바꾸기
- [x] 회원가입하고 바로 카트누르면 흰화면 되는 이슈 수정
- [x] 카트의 결제버튼이 카트에 아무것도 없으면 활성화 되지 않도록 수정
- [x] 결제하면 미니프로필하고 마이페이지에 금액 갱신시키기

## ETC
.
