### ISSUE TITLE
Refactor: Icon Atom 클래스명 수정

### ISSUE THREAD

**Issue by seungmin2ee** [starplanter93/The_Garden_of_Musicsheet#21]
## Description
scss 모듈을 적용함에 따라 기존에 BEM방식으로 작성된 클래스명을 간단한 형태로 수정

## Todo
- [x] Icon Atom의 scss 모듈화
- [x] Icon Atom의 클래스명 수정
- [x] px -> rem 변경
