### ISSUE TITLE
[BE] 프리즈마 & 스웨거 초기 세팅

### ISSUE THREAD

**Issue by EthanJcoding** [starplanter93/The_Garden_of_Musicsheet#4]
## Description
프리즈마 초기 세팅, DB 연동은 차후 일단 스키마 먼저 세팅

## Todo
- [x] npm i prisma
- [x] schema 생성
- [x] EC2 DB 연결
- [ ] Github action deploy 부분에 `npx prisma generate dev` 추가

- [x] npm i Express Swagger
- [x] 환경 세팅 및 링크 공유 

- [x] 프리즈마 클라이언트 세팅

## ETC
- [x] 경호님 EC2에 DB 여시면 연동 예정
