### ISSUE TITLE
Feat: Header organism 구현

### ISSUE THREAD

**Issue by seungmin2ee** [starplanter93/The_Garden_of_Musicsheet#50]
## Description
로고와 메뉴, 로그인 버튼(로그인시 유틸메뉴)로 구성된 Header organism 구현

## Todo
- [x] 레이아웃, 스타일, 스토리 작성
- [x] 로그인 여부에 따라 표시되는 UI 분기
- [x] 드롭다운 메뉴의 외부 영역 클릭시 닫는 기능 구현
