### ISSUE TITLE
[BE] 로그인 구현 초기 세팅

### ISSUE THREAD

**Issue by EthanJcoding** [starplanter93/The_Garden_of_Musicsheet#6]
## Description
nestjs/jwt 패키지를 사용한 JWT 인증 방식의 로그인 구현

## Todo
- [x] nestjs/jwt  패키지 다운로드
- [x] 회원가입, 로그인 기능구현
- [x] bycrypt 패키지를 사용하여 비밀번호 암호화
- [ ] 토큰 생성 검증하기
- [ ] guard를 이용한 토큰 인증하기
- [ ] role guard를 이용한 권한 관리하기

## ETC
테스트 끝나고 머지 예정
