### ISSUE TITLE
Feat: 전역 상태 유지를 위한 redux-persist 적용

### ISSUE THREAD

**Issue by seungmin2ee** [starplanter93/The_Garden_of_Musicsheet#71]
## Description
유저 정보 또는 장바구니의 전역 상태가 새로고침하여도 유지될 수 있도록 redux-persist 적용

## Todo
- [x] redux-persist 라이브러리 설치 및 초기 설정
- [x] 로그인시 유저 정보를 받아와 로컬스토리지의 영속 상태에 저장
- [x] 로그아웃시 로컬스토리지의 유저 정보 영속상태를 초기화
