### ISSUE TITLE
Feat: 유저 정보 핸들링 및 악보 PDF 업로드

### ISSUE THREAD

**Issue by EthanJcoding** [starplanter93/The_Garden_of_Musicsheet#77]
## Description
auth.currentUser 메서드를 활용하여 내부 정보 조작

## Todo
- [x] phoneNumber 값에 객체를 넣고 유저의 캐시정보와 해당 유저가 작성한 글들의 정보를 담기 (역시나 실패😭...)
- [x] 위의 투두로 해결이 안된다면, DB에 유저 테이블을 작성하고 post 할 때 마다 그쪽에도 데이터 추가하기

- [x] 유저가 저장하기 버튼을 누르면 등록한 PDF 파일이 Storage에 저장되고 해당 다운로드 URL을 postData에 넣어서 악보 등록
- [x] 처음에 등록한 악보의 이름을 수정하려고 했지만 Readonly 임
- [x] 따로 PDF 파일을 수정하지말고 그냥 다운로드 URL만 받아서 넘겨주기

## ETC
기타사항
