### ISSUE TITLE
Feat: 장바구니 모달 organsim 및 구성 molecule 구현

### ISSUE THREAD

**Issue by seungmin2ee** [starplanter93/The_Garden_of_Musicsheet#87]
## Description
장바구니 모달과 구성 컴포넌트를 구현합니다.

## Todo
- [x] 상단바 molecule
- [x] 하단바 molecule
- [x] 장바구니 목록 molecule
- [x] 장바구니 모달 organism
- [x] 장바구니 모달 상태 redux 구현
- [x] 장바구니 모달에 데이터 추가기능 구현
- [x] 장바구니 모달에 데이터 제거기능 구현
- [x] 파이어베이스와 장바구니 모달 연동
- [x] 결제 후 유저 정보에 구입한 악보정보 추가
- [x] 결제 후 유저 정보에서 캐시 차감 기능 구현
