### ISSUE TITLE
Feat: 마이페이지 제작

### ISSUE THREAD

**Issue by EthanJcoding** [starplanter93/The_Garden_of_Musicsheet#90]
## Description
유저가 본인이 작성한 게시글과 구매한 게시글을 구분하여 볼 수 있는 페이지입니다.
유저는 이곳에서 자신의 프로필 이미지와 닉네임을 변경할 수 있고 회원탈퇴를 할 수 있습니다.

## Todo
- [x] 기존에 만들어진 CategoryCover 를 재사용하여 마이페이지 상단 구현
- [x] 기존에 만들어진 Tabmenu 를 재사용하여 데이터 필터링 구현 ( 작성 게시글 & 구매 내역 )
- [x] 유저테이블에서 작성한 글을 fetching하여 ScoreList 를 재사용하여 중단 컨텐츠 제작 
---
Droped => 드랍하려다가 다른 방법이 떠올라서 성공
- [x] 유저가 프로필 이미지를 수정하기 위해서 유저 테이블에 photoURL 필드를 추가하고 업로드 로직 구현 ❌
- [x] 닉네임은 파이어베이스의 내장 매서드를 사용하여 간단하게 구현 ( .updateProfile ) ❌
- [x] user, music, inst 파이어베이스 컬렉션 업데이트
---
- [x] 회원탈퇴역시 파이어베이스의 내장 매서드를 사용 ( .delete )  ❌
- [x] 회원 탈퇴시 isOptout 필드를 이용하여 true 로 업데이트 되게 구현 ( 데이터 뿌려주는 곳에서 해당 필드를 사용하여 분기 )
- [x] user, music, inst 파이어베이스 업데이트

## ETC
구매 페이지 구현이 끝나고 구매 이력 data fetching
프로필 사진을 저장할 경로 생성
